const populerData = [
  {
    id: "01001",
    category: "kerajinan",
    img: "/assets/images/KERAJINANtempurungkelapa.jpeg",
    alt: "Peralatan Minum dari Tempurung Kelapa",
    title: "Peralatan Minum dari Tempurung Kelapa",
    price: "Rp. 90.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01002",
    category: "kerajinan",
    img: "/assets/images/KerajinanTopengsouvenir.jpeg",
    alt: "Gantungan Kunci Topeng Tradisional Sanggar Jaka Baru",
    title: "Gantungan Kunci Topeng Tradisional Sanggar Jaka Baru",
    price: "Rp. 17.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01003",
    category: "kerajinan",
    img: "/assets/images/celengan.jpeg",
    alt: "Celengan Kayu Handmade",
    title: "Celengan Kayu Handmade",
    price: "Rp. 70.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "01004",
    category: "kerajinan",
    img: "/assets/images/hiasanrumah.jpeg",
    alt: "Kerajinan Tempurung Kelapa untuk Hiasan Rumah",
    title: "Kerajinan Tempurung Kelapa untuk Hiasan Rumah",
    price: "Rp. 85.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "",
    category: "kerajinan",
    img: "public/assets/images/wayangsemar.jpeg",
    alt: "Wayang Semar Buatan Tangan",
    title: "Wayang Semar Buatan Tangan",
    price: "Rp. 170.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01006",
    category: "kerajinan",
    img: "/assets/images/RotanGajahTempatPermen.jpeg",
    alt: "Rotan Gajah Tempat Permen",
    title: "Rotan Gajah Tempat Permen",
    price: "Rp. 230.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "01007",
    category: "kerajinan",
    img: "/assets/images/anting.jpeg",
    alt: "Anting dari Tempurung Kelapa",
    title: "Anting dari Tempurung Kelapa",
    price: "Rp. 25.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "01008",
    category: "kerajinan",
    img: "/assets/images/anyamanecenggondok.jpeg",
    alt: "Keranjang Anyaman Eceng Gondok",
    title: "Keranjang Anyaman Eceng Gondok",
    price: "Rp. 200.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "01009",
    category: "kerajinan",
    img: "/assets/images/hiasandinding.jpeg",
    alt: "Hiasan Dinding Ukiran Kayu Asli Buatan Tangan",
    title: "Hiasan Dinding Ukiran Kayu Asli Buatan Tangan",
    price: "Rp. 150.000",
    rating: 5,
    isNew: true,
  },
  {
    id: "02001",
    category: "makanan",
    img: "public/assets/images/M_gethuk.jpg",
    alt: "Gethuk khas Jawa Tengah",
    title: "Gethuk khas Jawa Tengah",
    price: "Rp. 3.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02002",
    category: "makanan",
    img: "public/assets/images/M_onde2Jawa.jpeg",
    alt: "Onde-onde khas Jawa Tengah (per pcs)",
    title: "Onde-onde khas Jawa Tengah (per pcs)",
    price: "Rp. 3.500",
    rating: 4,
    isNew: true,
  },
  {
    id: "02003",
    category: "makanan",
    img: "public/assets/images/M_ Wajik.jpeg",
    alt: "Wajik khas Jawa Tengah (per pcs)",
    title: "Wajik khas Jawa Tengah (per pcs)",
    price: "Rp. 2.500",
    rating: 4,
    isNew: true,
  },
  {
    id: "02004",
    category: "makanan",
    img: "public/assets/images/M_lumpiaSemarang.jpeg",
    alt: "Lumpia asli Semarang (per pcs)",
    title: "Lumpia asli Semarang (per pcs)",
    price: "Rp. 10.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02005",
    category: "makanan",
    img: "public/assets/images/M_wingkoBabat.jpeg",
    alt: "Wingko babat asli Jawa Tengah (per pcs)",
    title: "Wingko babat asli Jawa Tengah (per pcs)",
    price: "Rp. 7.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02006",
    category: "makanan",
    img: "public/assets/images/M_serabiSolo.jpeg",
    alt: "Serabi Solo (per pcs)",
    title: "Serabi Solo (per pcs)",
    price: "Rp. 3.500",
    rating: 4,
    isNew: true,
  },
  {
    id: "02007",
    category: "makanan",
    img: "public/assets/images/M_JenangMubarok.jpeg",
    alt: "Jenang Kudus Mubarok (per box)",
    title: "Jenang Kudus Mubarok (per box)",
    price: "Rp. 20.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02008",
    category: "makanan",
    img: "public/assets/images/M_Rotiganjelrel.jpeg",
    alt: "Roti ganjel rel khas Semarang (per pcs)",
    title: "Roti ganjel rel khas Semarang (per pcs)",
    price: "Rp. 10.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "02009",
    category: "makanan",
    img: "public/assets/images/M_latopiategal.jpg",
    alt: "Latopia Tegal Ny.LIAO (per box)",
    title: "Latopia Tegal Ny.LIAO (per box)",
    price: "Rp. 20.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03001",
    category: "pakaian",
    img: "/assets/images/P_BATIKSOLO.jpeg",
    alt: "Kemeja batik Solo",
    title: "Kemeja batik Solo",
    price: "Rp. 250.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03002",
    category: "pakaian",
    img: "/assets/images/P_KEMEJABATIKBIRU.jpeg",
    alt: "Kemeja batik biru",
    title: "Kemeja batik biru",
    price: "Rp. 280.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03003",
    category: "pakaian",
    img: "/assets/images/P_BATIKMARK.jpeg",
    alt: "Kemeja batik Kebumen",
    title: "Kemeja batik Kebumen",
    price: "Rp. 275.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03004",
    category: "pakaian",
    img: "/assets/images/P_BATIKBLAZER.jpeg",
    alt: "Blazer batik wanita",
    title: "Blazer batik wanita",
    price: "Rp. 280.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03005",
    category: "pakaian",
    img: "public/assets/images/P_BAJULURIK.jpg",
    alt: "Baju surjan/lurik",
    title: "Baju surjan/lurik",
    price: "Rp. 170.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03006",
    category: "pakaian",
    img: "public/assets/images/P_KEBAWAJADUL.jpeg",
    alt: "Satu set baju kebaya jadul",
    title: "Satu set baju kebaya jadul",
    price: "Rp. 400.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03007",
    category: "pakaian",
    img: "public/assets/images/P_BATIKORIGINAL.jpeg",
    alt: "Baju batik wanita original",
    title: "Baju batik wanita original",
    price: "Rp. 300.000",
    rating: 4,
    isNew: true,
  },
  {
    id: "03008",
    category: "pakaian",
    img: "public/assets/images/P_BLOUSEBIRU.jpeg",
    alt: "Blouse batik kekinian",
    title: "Blouse batik kekinian",
    price: "Rp. 290.000",
    description: "Tampil trendi dengan blouse batik kekinian yang memadukan motif tradisional dengan sentuhan desain modern.",
    rating: 4,
    isNew: true,
  },
  {
    id: "03009",
    category: "pakaian",
    img: "public/assets/images/P_NonararaBatik.jpeg",
    alt: "Nonarara batik",
    title: "Nonarara batik",
    price: "Rp. 250.000",
    rating: 4,
    isNew: true,
  },
];

export default populerData;
