export const ADataMakanan = [
  {
    id: 1,
    name: 'Jenang Kudus Senar Tiga',
    description: 'Kue tradisional dari Kudus dengan rasa manis dan tekstur kenyal.',
    price: 12000,
    image: '/assets/images/ajenang.png',
    category: 'Makanan Tradisional',
    stock: 'Tersedia',
    color: 'Coklat Muda',
    size: '250 gram',
    material: 'Bahan dasar tepung ketan, gula, dan santan',
  },
  {
    id: 2,
    name: 'Lumpia Asli Semarang',
    description: 'Lumpia Semarang dengan isian daging ayam dan sayuran yang gurih.',
    price: 10000,
    image: '/assets/images/alumpia.png',
    category: 'Makanan Tradisional',
    stock: 'Tersedia',
    color: 'Coklat Kekuningan',
    size: '2 pcs per porsi',
    material: 'Kulit lumpia, daging ayam, sayuran',
  },
  {
    id: 3,
    name: 'Roti Ganjel',
    description: 'Roti khas Indonesia yang lezat dengan rasa manis dan kenyal.',
    price: 10000,
    image: '/assets/images/aganjel.png',
    category: 'Roti Tradisional',
    stock: 'Tersedia',
    color: 'Coklat Tua',
    size: '1 buah',
    material: 'Bahan dasar tepung, gula merah, dan santan',
  },
  {
    id: 4,
    name: 'Kerupuk Capret Cap Raden',
    description: 'Kerupuk khas dengan rasa gurih dan renyah, cocok sebagai camilan.',
    price: 8000,
    image: '/assets/images/akrupuk.png',
    category: 'Camilan',
    stock: 'Tersedia',
    color: 'Putih',
    size: '100 gram',
    material: 'Bahan dasar tepung tapioka',
  },
  {
    id: 5,
    name: 'Wingko Babat',
    description: 'Kue tradisional khas Semarang berbahan kelapa dan ketan, manis dan kenyal.',
    price: 7000,
    image: '/assets/images/awingko.png',
    category: 'Makanan Tradisional',
    stock: 'Tersedia',
    color: 'Kuning Kecoklatan',
    size: '1 buah',
    material: 'Bahan dasar kelapa parut dan tepung ketan',
  },
  {
    id: 6,
    name: 'Serabi Solo',
    description: 'Pancake tradisional Solo dengan rasa gurih dan toping kelapa parut.',
    price: 3500,
    image: '/assets/images/aserabi.png',
    category: 'Makanan Tradisional',
    stock: 'Tersedia',
    color: 'Putih Kekuningan',
    size: '1 buah',
    material: 'Tepung beras, santan, kelapa parut',
  },
  {
    id: 7,
    name: 'Onde-Onde',
    description: 'Camilan tradisional isi kacang hijau dengan lapisan wijen yang renyah.',
    price: 3500,
    image: '/assets/images/aonde.png',
    category: 'Camilan Tradisional',
    stock: 'Tersedia',
    color: 'Emas',
    size: '1 buah',
    material: 'Kacang hijau, tepung ketan, wijen',
  },
  {
    id: 8,
    name: 'Gethuk Khas Jawa Tengah',
    description: 'Gethuk manis khas Jawa Tengah terbuat dari singkong yang kenyal.',
    price: 3500,
    image: '/assets/images/agethuk.png',
    category: 'Makanan Tradisional',
    stock: 'Tersedia',
    color: 'Putih',
    size: '250 gram',
    material: 'Singkong, gula, pewarna makanan',
  },
  {
    id: 9,
    name: 'Wajik Khas Jawa Tengah',
    description: 'Kue wajik manis berbahan ketan dengan rasa gula merah yang khas.',
    price: 2500,
    image: '/assets/images/awajik.png',
    category: 'Makanan Tradisional',
    stock: 'Tersedia',
    color: 'Coklat',
    size: '200 gram',
    material: 'Ketan, gula merah, santan',
  },
];

export default ADataMakanan;
